name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe
version: 1.0.0+1
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.2+1
  geolocator: ^6.1.9 # for location servies
  url_launcher: ^5.7.10 # for opening the googlemap url
  geocoder: ^0.2.1

  firebase_auth: ^0.15.4
  google_fonts: 0.1.1
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  firebase_storage: ^3.1.1
  flutter_staggered_grid_view: ^0.3.0
  mask_text_input_formatter: ^1.0.7
  location: ^3.0.0
  provider: ^4.0.4
  path_provider: ^1.4.0
  firebase_core: ^0.4.0
  image: ^2.0.7
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^0.19.1
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - images/welcome.png
    - images/homelocation.png
    - images/Location.svg
    - images/address1.PNG
    - images/logout.svg
    - images/login.png
    - images/Discovery.svg
    - images/bags.png
    - images/key.svg
    - images/admin.png
    - images/cash.png
    - images/search.png
    - images/noSearch.svg
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - images/login_bottom.png
    - images/main_bottom.png
    - images/main_top.png
    - images/signup_top.png
    - images/chat.svg



